source "https://rubygems.org"

gem "jekyll", "4.3.3"
gem 'csv'
gem 'base64'
gem 'stringio'
gem 'time'
gem 'date'
gem 'uri'
gem 'json'
gem 'openssl'
gem 'zlib'
gem 'fileutils'
gem 'pathname'
gem 'tempfile'
gem 'yaml'

group :jekyll_plugins do
  gem "jekyll-bookshop", "3.9.0"
  gem 'jekyll-tagging', "1.1.0"
  gem "jekyll-sitemap", "1.4.0"
end
